services:
  redis7:
    image: redis:7
    container_name: redis.dap.test
    restart: 'no'
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning --requirepass apps
    volumes:
      - ~/volumes/redis7:/data
      - ./shared:/var/www/shared # Shared directory between containers.
